import './global.css'
import './layout.css'

import './themes/default.css'
import './themes/red.css'
import './themes/blue.css'

import './components/a.css'
import './components/button.css'
import './components/card.css'
import './components/input.css'
import './components/markdown.css'
import './components/small.css'
import './components/textarea.css'
import './components/titles.css'
import './components/tabs.css'
